set_property SRC_FILE_INFO {cfile:g:/system/NewCPU/NewCPU.gen/sources_1/ip/ROM_D/ROM_D/ROM_D_in_context.xdc rfile:../../../../../NewCPU.gen/sources_1/ip/ROM_D/ROM_D/ROM_D_in_context.xdc id:1 order:EARLY scoped_inst:U2_ROM_D} [current_design]
set_property SRC_FILE_INFO {cfile:g:/system/NewCPU/NewCPU.gen/sources_1/ip/RAM_B/RAM_B/RAM_B_in_context.xdc rfile:../../../../../NewCPU.gen/sources_1/ip/RAM_B/RAM_B/RAM_B_in_context.xdc id:2 order:EARLY scoped_inst:U3_RAM_B} [current_design]
set_property SRC_FILE_INFO {cfile:G:/system/sources/icf.xdc rfile:../../../../../../sources/icf.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U2_ROM_D]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins U3_RAM_B/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U3_RAM_B]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 100.000 -name sys_clk_pin -waveform {0.000 50.000} -add [get_ports clk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U2_ROM_D]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U3_RAM_B]
